name: IoTManager - Build and Deploy to Docker Container Registry

on:
  push:
    branches: [main]

jobs:
  build_go120:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: build_and_push_go120
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386,linux/amd64,linux/arm64,linux/ppc64le,linux/arm/v6,linux/arm/v7,linux/s390x
          push: true
          build-args: |
            TAG=latest
          tags: |
            vistart/iotmanager:latest
      -
        name: Image digest
        run: echo ${{ steps.build_and_push_go120.outputs.digest }}